### PR TITLE
Added a methods to  unit of work to be able to register record for up…

### PR DESCRIPTION
**Pull request by yurybond**
A couple of methods to simplify committing lists of records that have as new as existing records

### CODE REVIEW

**Comment by yurybond** [comment]
@dfruddffdc Could you please review this pull-request?

**Comment by afawcett** [comment]
This look like useful additions to me! 👍

**Comment by yurybond** [comment]
@dfruddffdc  Hey guys do you have an idea when pull requests from queue can be merged to master? 
Who is doing merges to this repo?

**Comment by yurybond** [comment]
@agarciaffdc thank you for approval this pull request. Do you have an idea when it will be released?

**Comment by yurybond** [comment]
@agarciaffdc I will be happy to help, but for now I do not see any conflicts between my branch and master. Could you please let me knwo how can I help to resolve conflict? Where to retrieve your latest changes (do  not see any update of master since Apr 16)?

**Comment by agarciaffdc** [comment]
I'm sorry, it seems to be something else related with deploy. We will try to solve it asap, but with CX break, I'm pretty sure we would not be able to merge branches till January.

**Comment by yurybond** [comment]
Hi  @agarciaffdc , will you be able to merge this pull request by chance?

**Comment by agarciaffdc** [comment]
@yurybond I will do it  this week. Sorry for the delay

**Comment by agarciaffdc** [comment]
@yurybond your branch is merged finally. I'm really sorry for the big delay. Hope next time the process will be smother. Thank you so much for your contribution

**Pull request merged**
