### PR TITLE
Fix Code Styling

### PR DESCRIPTION
**Pull request by wimvelzeboer**
Applied code styling (braces, indents, etc), PMD Apex and fixed typo's

### CODE REVIEW

**Comment by afawcett** [comment]
@wimvelzeboer this is great work thanks taking the time to do this, I know @rsoesemann will be happy!

**Comment by afawcett** [comment]
@dfruddffdc @agarciaodeian any thoughts on this? It would be great to get the lib compliant with PMD! 👍

**Comment by rsoesemann** [comment]
You know how happy I am when you spread the word about Clean Code and PMD...but in this PR it's only used for a few IMHO less important cosmetic changes. More relevant issues found by PMD in this lib are long complex classes. Hard to testcover conditional structures and an overuse of static vs good OO encapsulation patterns.

Don't get me wrong. I love this lib for what it does and how great it scales but the complex code gave me a hard time whenever I wanted to contribute.

**Comment by afawcett** [comment]
Thanks for the clarification @rsoesemann, small steps...

**Comment by wimvelzeboer** [comment]
I could have a look at the more important PMD issues if you like, but in this commit I focused on styling. I know that it is best to do not too many things in one pull-request when it comes to styling, else we might run into very complex merges.

**Comment by rsoesemann** [comment]
@wimvelzeboer That was not at all criticism of your first step. I fully agree with you that before you fix design issues in code "low hanging fruits" like naming and formatting should be fixed.

My answer to @afawcett was twofold: Me highly appreciating the adoption of PMD in such a wellknown repo and the wish to make this lib a bit less verbose and complex so other devs could contribute more.

And I think that PMDs Cyclomatic Complexity, To Long Class, To many methods, To much static stuff rules could help refactor it. But someone with deep insights into the existing code would need to do this. So not me ;-)

**Comment by afawcett** [comment]
If these changes are reduce PMD output and move us a step closer to enabling PMD i am up for it. @wimvelzeboer  can you confirm?

**Pull request closed without merging**
