### PR TITLE
Use StringBuilder in the QueryFactory

### PR DESCRIPTION
**Pull request by ForceComDeveloper**
Modification of the StringBuilder : 
* Added a constructor with single string
* Added remove method
* Added size method

Modification in the QueryFactory : 
* toSOQL implemented with StringBuilder

Added a Benchmarker tool

### CODE REVIEW

**Comment by capeterson** [comment]
I see you added a new apex class that seems to be related to benchmarking, did you do any work to see if using a StringBuilder helps or hurts performance? I know it's a best practice in java, but in apex it seems less clear cut (method calls are more expensive for one) and I'm interested in hearing your results, if you have any.

That said, the huge amount of whitespace-only diffs are a bit of a problem for merging, and `Benchmarker` seems like it would need some work and tests to be accepted. Is it meant to be part of this PR?

**Comment by ForceComDeveloper** [comment]
Hi Chris,

I've added a controller and a page to visualize the Benchmarker in action.

How can I add it to my pull request ?

**Comment by afawcett** [comment]
This is great work! What are the results showing in terms of QueryFactory with and without use of StringBuilder? 

BTW, i think the benchmarker code here is something we would want in a separate repo rather than in this library. I'm working with another community member on splitting up fflib a bit into a core lib and some addon libs, so this might be one such addon lib. 

@capeterson  This is something i've added to our next catchup.

**Comment by ForceComDeveloper** [comment]
Hi Andrew,

Thank you.
I think it is a little bit tricky to test it because related code to test
are in another repository.

To test it, I have both classes (yours and mine) in the same org and I try
to build a simple query with it.
Do you have a sample of code enabling to have a query with inner and outer
subselect (to have large query) without having to merge repo common and
sample ?

++

**Comment by tfuda** [comment]
This would be a good use case for a continuous integration set up that
deploys latest code from github into a DE org. The benchmarking code could
be deployed there too.

**Comment by afawcett** [comment]
There are some complex queries in the sample app, see OpportunitiesSelector. In your tests so far, do you see any significant difference?

**Comment by afawcett** [comment]
@ForceComDeveloper there is some great work here, but this PR has become a little complex with multiple things in it, let me try to summarise...

- The main part of this is a performance improvement, i think if this is for sure going to benifit and you can prove with some more complex examples (as per my last comment there are a few in the sample app repo), then i'd be happy to accept a PR for just the changes to the query factory class.
- There is also a change to 'Fixing IdSet implementation of the memoization pattern', did you have any thoughts on my response to this change? Again, it would be good if you want to progress that to open that as its own issue and PR if so.
- Finally you have written what looks like an excellent benchmarking framework, worth of its own repo in my view. Have you thought about perhaps hosting on your own GitHub account. With the CPU Governor being more and more the controlling factor, I think there is a gap that needs to be filled for tools and approaches that help measure execution times btw.

So please do not take this as my wanting to dismiss any of this, quite the opposite! :+1:  But i think its best if we close this PR and review next steps in respect to the items above. Hope this makes sense and please do keep supporting this library, really do appreciate it, look forward to your thoughts!

**Comment by ForceComDeveloper** [comment]
Bonjour financialforcedev/fflib-apex-common,
Sebastien Colladon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/z8pJaH/ukh/?hg=BLWDpeq7cT pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=aff2a1fe&email=reply@reply.github.com.&hg=BLWDpeq7cT
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by ForceComDeveloper** [comment]
Bonjour financialforcedev/fflib-apex-common,
Sebastien Colladon vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/z8pJaH/eam/?hg=BLWDpeq7cT pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=5f36bcd3&email=reply@reply.github.com.&hg=BLWDpeq7cT
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by ForceComDeveloper** [comment]
Bonjour financialforcedev/fflib-apex-common,


Sebastien Colladon vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/z8pJaH/eam/?hg=SlG7xbHLKj pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=5f36bcd3&email=reply@reply.github.com.&hg=SlG7xbHLKj
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Comment by ForceComDeveloper** [comment]
Bonjour financialforcedev/fflib-apex-common,


Sebastien Colladon vous a laissé un message sur IQ Elite 


Cliquez ici a.iqelite.com/j/z8pJaH/ukh/?hg=SlG7xbHLKj pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=aff2a1fe&email=reply@reply.github.com.&hg=SlG7xbHLKj
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------

**Pull request closed without merging**
